from __future__ import annotations

import argparse
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
from pypdf import PdfReader, PdfWriter
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas


TITLE = "Synthetic Signals in Deterministic Literature Workflows"
AUTHORS = "Ada Example; Lin Test"


def _font(size: int):
    return ImageFont.load_default(size=size)


def _article_image(*, screenshot: bool) -> Image.Image:
    image = Image.new("RGB", (1240, 1754), "white")
    draw = ImageDraw.Draw(image)
    top = 0
    if screenshot:
        draw.rectangle((0, 0, 1240, 115), fill="#e8eaed")
        draw.ellipse((28, 35, 58, 65), fill="#ea4335")
        draw.ellipse((72, 35, 102, 65), fill="#fbbc04")
        draw.ellipse((116, 35, 146, 65), fill="#34a853")
        draw.rounded_rectangle((190, 22, 1180, 84), radius=18, fill="white")
        draw.text((220, 37), "https://example.invalid/article/fixture", fill="#5f6368", font=_font(24))
        top = 145
        draw.rectangle((0, 115, 1240, 145), fill="#1a73e8")
    margin = 105
    draw.text((margin, top + 95), TITLE, fill="black", font=_font(44))
    draw.text((margin, top + 170), AUTHORS, fill="#303030", font=_font(28))
    draw.line((margin, top + 225, 1135, top + 225), fill="#777777", width=3)
    draw.text((margin, top + 270), "Abstract", fill="black", font=_font(31))
    body = [
        "This page is generated by LAM and contains no third-party article text.",
        "It tests deterministic OCR routing, title extraction, and page classification.",
        "The stable fixture DOI is intentionally absent so no provider query is implied.",
        "Keywords: synthetic fixture; OCR; local archives; reproducible testing.",
    ]
    y = top + 330
    for line in body:
        draw.text((margin, y), line, fill="black", font=_font(24))
        y += 58
    draw.rectangle((margin, y + 55, 1135, y + 360), outline="#444444", width=3)
    draw.text((margin + 30, y + 90), "Figure 1. Synthetic layout region", fill="black", font=_font(25))
    draw.line((margin + 55, y + 300, 1080, y + 145), fill="#1a73e8", width=8)
    draw.text((margin, 1665), "LAM synthetic corpus - page 1", fill="#555555", font=_font(20))
    return image


def _png_bytes(image: Image.Image) -> bytes:
    buffer = BytesIO()
    image.save(buffer, format="PNG", optimize=False, compress_level=9)
    return buffer.getvalue()


def _canvas(path: Path, *, title: str = TITLE, author: str = AUTHORS) -> canvas.Canvas:
    target = canvas.Canvas(
        str(path), pagesize=A4, invariant=1, pageCompression=0
    )
    target.setTitle(title)
    target.setAuthor(author)
    target.setCreator("LAM synthetic test corpus generator")
    return target


def native_text(path: Path) -> None:
    pdf = _canvas(path)
    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(54, 770, TITLE)
    pdf.setFont("Helvetica", 11)
    pdf.drawString(54, 742, AUTHORS)
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(54, 700, "Abstract")
    pdf.setFont("Helvetica", 10)
    pdf.drawString(54, 680, "A project-generated native text fixture for deterministic PDF extraction.")
    pdf.drawString(54, 662, "No real publication content or external identifier is included.")
    pdf.showPage()
    pdf.save()


def raster_pdf(path: Path, *, screenshot: bool) -> None:
    pdf = _canvas(path, title="", author="")
    image = ImageReader(BytesIO(_png_bytes(_article_image(screenshot=screenshot))))
    pdf.drawImage(image, 0, 0, width=A4[0], height=A4[1], preserveAspectRatio=False)
    pdf.showPage()
    pdf.save()


def contaminated_metadata(path: Path) -> None:
    temporary = path.with_suffix(".base.pdf")
    native_text(temporary)
    reader = PdfReader(temporary)
    writer = PdfWriter()
    for page in reader.pages:
        writer.add_page(page)
    writer.add_metadata(
        {
            "/Title": "Download PDF | Journal Viewer | https://example.invalid/article",
            "/Author": "Sign in Subscribe Cookie preferences",
            "/Subject": "navigation header footer download full text",
            "/Creator": "LAM synthetic contaminated metadata fixture",
            "/Producer": "LAM deterministic fixture",
        }
    )
    with path.open("wb") as handle:
        writer.write(handle)
    temporary.unlink()


def generate(output: Path) -> None:
    output.mkdir(parents=True, exist_ok=True)
    native_text(output / "native_text.pdf")
    raster_pdf(output / "image_only.pdf", screenshot=False)
    raster_pdf(output / "screenshot_wrapped.pdf", screenshot=True)
    contaminated_metadata(output / "contaminated_metadata.pdf")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate deterministic LAM PDF fixtures")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "examples" / "test_corpus" / "included",
    )
    args = parser.parse_args()
    generate(args.output.resolve())
    print(f"generated synthetic PDF fixtures in {args.output.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
