from __future__ import annotations

from pathlib import Path
import tomllib

from lam.command_registry import (
    COMMANDS,
    COMPATIBILITY_COMMANDS,
    command_definition,
    command_markdown_table,
)
from lam.release_docs import AUTOGENERATED_NOTICE, render_cli_commands


def test_cli_reference_is_generated_from_public_registry():
    source_root = Path(__file__).resolve().parents[1]
    generated = (source_root / "docs" / "CLI_COMMANDS.md").read_text(encoding="utf-8")

    assert generated == render_cli_commands()
    assert generated.startswith(AUTOGENERATED_NOTICE)
    for definition in COMMANDS:
        assert definition.usage in generated
    for definition in COMPATIBILITY_COMMANDS:
        assert f"lam {definition.name}" not in generated


def test_readme_public_table_is_registry_generated():
    repository_root = Path(__file__).resolve().parents[2]
    readme = (repository_root / "README.md").read_text(encoding="utf-8")

    assert command_markdown_table() in readme


def test_registry_metadata_matches_nested_parser_contract():
    export = command_definition("export")
    recover = command_definition("recover")
    migrate = command_definition("migrate")
    cleanup = command_definition("cleanup")

    assert export.canonical_command == "export zotero"
    assert export.arguments.index("zotero") < export.arguments.index("--dry-run")
    assert export.arguments.index("--apply") < export.arguments.index("--all")
    assert recover.arguments.index("--list-trash") < recover.arguments.index("--scope")
    assert migrate.arguments.index("schema|identifiers|topics") < migrate.arguments.index(
        "--dry-run"
    )
    assert cleanup.modifies_managed_files is True


def test_root_agent_workflow_documents_match_packaged_templates():
    repository_root = Path(__file__).resolve().parents[2]
    resources = repository_root / "LAM_tools" / "src" / "lam" / "resources"

    for name in ("AGENTS.md", "Workflows.md"):
        assert (repository_root / name).read_bytes() == (resources / name).read_bytes()


def test_package_metadata_includes_document_templates():
    source_root = Path(__file__).resolve().parents[1]
    package = tomllib.loads((source_root / "pyproject.toml").read_text(encoding="utf-8"))
    compatibility = tomllib.loads(
        (source_root.parent / "pyproject.toml").read_text(encoding="utf-8")
    )

    expected = ["resources/*.md"]
    assert package["tool"]["setuptools"]["package-data"]["lam"] == expected
    assert compatibility["tool"]["setuptools"]["package-data"]["lam"] == expected
