from __future__ import annotations

from pathlib import Path

from .command_registry import COMMANDS, CommandDefinition


AUTOGENERATED_NOTICE = (
    "<!-- Generated by scripts/generate_cli_docs.py from lam.command_registry. "
    "Do not edit by hand. -->"
)


def _yes_no(value: bool) -> str:
    return "yes" if value else "no"


def _display_name(item: CommandDefinition) -> str:
    return "export zotero" if item.name == "export" else item.name


def render_cli_commands() -> str:
    lines = [
        AUTOGENERATED_NOTICE,
        "",
        "# LAM public CLI commands",
        "",
        "This file is generated from the public command registry. The parser is the",
        "executable grammar; the registry publishes command capabilities, supported",
        "arguments, status codes, and canonical identities. Hidden compatibility",
        "commands are intentionally excluded.",
        "",
        "## Global contract",
        "",
        "Global options are `--root`, `--json`, `--verbose`, and `--caller` and may",
        "appear before or after the top-level command. Agent calls pass `--caller",
        "agent`. Daily commands apply by default and accept optional `--dry-run`;",
        "maintenance and migration operations require exactly one of `--dry-run` or",
        "`--apply`; diagnostics expose neither mode. A dry run may write runtime",
        "reports, logs, cache entries, and invocation records, but does not commit",
        "Catalogue, Documents, managed files, snapshots, operation journals, or",
        "`library_changes.md`.",
        "",
        "Every dispatched command supports `--json`. Its single stdout object uses",
        "schema version 1 and fields `schema_version`, `command`,",
        "`canonical_command`, `status`, `exit_code`, `errors`, `warnings`,",
        "`report_path`, `invocation_id`, and `details`.",
        "",
        "## Command matrix",
        "",
        "| Command | Mode | Business state | Runtime | Managed files | Catalogue | Export files | Network / cache | Final check | Exit codes |",
        "|---|---|---:|---:|---:|---:|---:|---|---:|---|",
    ]
    for item in COMMANDS:
        network = item.network_contract or ("network capable" if item.uses_network else "local only")
        if item.writes_cache:
            network += "; writes cache"
        lines.append(
            f"| `lam {_display_name(item)}` | {item.mode_contract} | "
            f"{_yes_no(item.modifies_business_state)} | "
            f"{_yes_no(item.writes_runtime_artifacts)} | "
            f"{_yes_no(item.modifies_managed_files)} | "
            f"{_yes_no(item.modifies_catalogue)} | "
            f"{_yes_no(item.writes_export_artifacts)} | {network} | "
            f"{_yes_no(item.runs_final_check)} | "
            f"{', '.join(str(code) for code in item.actual_exit_codes)} |"
        )

    lines.extend(
        [
            "",
            "Business-state read-only commands may still write runtime artifacts.",
            "`export zotero` writes regenerable export artifacts, not library business",
            "state. Registry network flags are conservative maxima; the conditional",
            "rules in the table state when a request is actually possible.",
            "",
            "## Command reference",
            "",
        ]
    )
    for item in COMMANDS:
        lines.extend(
            [
                f"### `lam {_display_name(item)}`",
                "",
                item.purpose + ".",
                "",
                f"- Usage: `{item.usage}`",
                f"- Workflow: {item.workflow}; category: {item.category}.",
                f"- Mode: {item.mode_contract}.",
                f"- Network: {item.network_contract}.",
                f"- Registry arguments, in parser order: `{', '.join(item.arguments)}`.",
            ]
        )
        if item.public_forms:
            forms = ", ".join(f"`lam {form}`" for form in item.public_forms)
            lines.append(f"- Canonical public forms: {forms}.")
        if item.aliases:
            aliases = ", ".join(f"`lam {alias}`" for alias in item.aliases)
            lines.append(f"- Canonical identity: {aliases}.")
        if item.name == "delete":
            lines.append(
                "- Agent safety: `--caller agent --apply` is refused; an agent may only preview deletion."
            )
        elif item.modifies_business_state:
            lines.append(
                "- Agent safety: pass `--caller agent` and follow the repository dry-run-first policy."
            )
        else:
            lines.append("- Agent safety: does not modify library business state.")
        lines.append("")

    lines.extend(
        [
            "## Status and exit codes",
            "",
            "Normal statuses are `success`, `needs_review`, `no_changes`, and",
            "`failed`. Exit codes are:",
            "",
            "- `0`: success.",
            "- `2`: completed with review items.",
            "- `3`: no changes.",
            "- `10`: parser, configuration, or lock error.",
            "- `20`: Catalogue error.",
            "- `30`: file-operation failure.",
            "- `40`: provider or network failure.",
            "",
            "A command advertises only the subset listed in its matrix row.",
            "",
            "## Generation and drift check",
            "",
            "From the standalone source root:",
            "",
            "```powershell",
            "python scripts/generate_cli_docs.py",
            "python scripts/generate_cli_docs.py --check",
            "```",
            "",
            "The release test suite also fails when this file, the README command table,",
            "or the packaged AGENTS/Workflows templates drift from their sources.",
            "",
        ]
    )
    return "\n".join(lines)


def write_cli_commands(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_cli_commands(), encoding="utf-8", newline="\n")
